USE [B2BTESTE2]
GO

IF Object_ID('tempDB..#API_PRODUTO_TMP','U') is not null DROP TABLE #API_PRODUTO_TMP;

GO

-- BUSCAR PROXIMO PRODUTO A IMPORTAR
PRINT 'CRIANO #API_PRODUTO_TMP'
SELECT TOP 1 * INTO #API_PRODUTO_TMP
	FROM API_PRODUTO
	WHERE (ID_PRODUTO IS NULL OR ID_PRODUTO='0') 
	  AND ID_DISTRIBUIDOR=1
	  AND STATUS_APROVADO='V'
	ORDER BY AGRUPAMENTO_VARIANTE, COD_FRAG_DISTR, COD_PROD_DISTR
;

GO

-- IMPORTAR FORNECEDOR
PRINT 'SALVANDO FORNECEDOR'
INSERT INTO FORNECEDOR
	SELECT  CONVERT(VARCHAR, ID_DISTRIBUIDOR)+'-'+COD_FORNECEDOR ID_FORNECEDOR,
			DESCRI_FORNECEDOR DESC_FORNECEDOR,
			'S' STATUS,
			GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM FORNECEDOR B
						WHERE B.ID_FORNECEDOR = CONVERT(VARCHAR, ID_DISTRIBUIDOR)+'-'+COD_FORNECEDOR)
;

GO

--CRIAR TIPO PADRAO CASO NAO TENHA NO FORNECEDOR
PRINT 'SALVANDO TIPO'
INSERT INTO TIPO
SELECT	A.ID_DISTRIBUIDOR,
		(SELECT ISNULL(MAX(ID_TIPO),0)+1 FROM TIPO) ID_TIPO,
		'CATEGORIAS' DESCRICAO,
		'A' STATUS,
		GETDATE() DATA_CADASTRO,
		'S' PADRAO
FROM #API_PRODUTO_TMP A
WHERE (SELECT ISNULL(MAX(ID_TIPO),0) FROM TIPO WHERE PADRAO='S' AND id_distribuidor IN (SELECT A.ID_DISTRIBUIDOR FROM #API_PRODUTO_TMP A))<=0;

GO

--IMPORTAR GRUPO CASO NAO TENHA
PRINT 'SALVANDO GRUPO'
INSERT INTO GRUPO
	SELECT  ID_DISTRIBUIDOR,
			CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_grupo id_grupo,
			(SELECT MAX(ID_TIPO) FROM TIPO C WHERE C.PADRAO='S' AND C.id_distribuidor = A.ID_DISTRIBUIDOR) tipo_pai,
			descr_grupo descricao,
			--CONVERT(VARCHAR, ID_DISTRIBUIDOR)+'-'+COD_FORNECEDOR ID_FORNECEDOR,
			--DESCRI_FORNECEDOR DESC_FORNECEDOR,
			'S' STATUS,
			GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM GRUPO B
						WHERE B.ID_GRUPO = CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_grupo
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR )
;

GO


--IMPORTAR SUBGRUPO CASO NAO TENHA
PRINT 'SALVANDO SUBGRUPO'
INSERT INTO SUBGRUPO
	SELECT  ID_DISTRIBUIDOR,
			CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_subgrupo id_subgrupo,
			descr_subgrupo descricao,
			'S' STATUS,
			GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM SUBGRUPO B
						WHERE B.id_subgrupo = CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_subgrupo
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR )
;

GO

--IMPORTAR SUBGRUPO CASO NAO TENHA
PRINT 'SALVANDO GRUPO-SUBGRUPO'
INSERT INTO GRUPO_SUBGRUPO
	SELECT  ID_DISTRIBUIDOR,
			CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_grupo id_grupo,
			CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_subgrupo id_subgrupo,
			'A' STATUS
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM GRUPO_SUBGRUPO GB
						WHERE GB.id_subgrupo = CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_subgrupo
						  AND GB.id_gruoe = CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_grupo,
						  AND GB.id_distribuidor = A.ID_DISTRIBUIDOR )
;

GO

--IMPORTAR MARCA CASO NAO TENHA
PRINT 'SALVANDO MARCA'
INSERT INTO MARCA
	SELECT  ID_DISTRIBUIDOR,
			CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_marca id_marca,
			descr_marca desc_marca,
			'S' STATUS,
			GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM MARCA B
						WHERE B.id_marca = CONVERT(VARCHAR, ID_DISTRIBUIDOR)+cod_marca
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR )
;

GO

--CRIAR ID DO PRODUTO UNICO
PRINT 'SALVANDO PRODUTO_DISTRIBUIDOR_ID'
INSERT INTO PRODUTO_DISTRIBUIDOR_ID
	SELECT  ID_DISTRIBUIDOR,
			ISNULL(AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, ID_DISTRIBUIDOR)+'-'+COD_PROD_DISTR) AGRUPAMENTO_VARIANTE,
			GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM PRODUTO_DISTRIBUIDOR_ID B
						WHERE B.AGRUPAMENTO_VARIANTE = ISNULL(A.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, A.ID_DISTRIBUIDOR)+'-'+COD_PROD_DISTR)
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR )
;

GO

-- IMPORTAR ESTRUTA PRODUTO_DISTRIBUIDOR
PRINT 'SALVANDO PRODUTO_DISTRIBUIDOR'
INSERT INTO PRODUTO_DISTRIBUIDOR
	SELECT  ID_DISTRIBUIDOR
		   ,(SELECT CONVERT(VARCHAR, ID_PRODUTO) FROM PRODUTO_DISTRIBUIDOR_ID B
						WHERE B.AGRUPAMENTO_VARIANTE = ISNULL(A.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, A.ID_DISTRIBUIDOR)+'-'+COD_PROD_DISTR)
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR) 
			+'-'+ 
			(SELECT CONVERT(VARCHAR, COUNT(*)+1) FROM PRODUTO_DISTRIBUIDOR C WHERE C.id_distribuidor = A.ID_DISTRIBUIDOR AND C.AGRUPAMENTO_VARIANTE=ISNULL(A.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, A.ID_DISTRIBUIDOR)+'-'+A.COD_PROD_DISTR) ) ID_PRODUTO
		   ,AGRUPAMENTO_VARIANTE
           ,COD_PROD_DISTR
           ,MULTIPLO_VENDA
           ,RANKING
           ,UNIDADE_VENDA
           ,QUANT_UNID_VENDA
           ,GIRO
           ,AGRUP_FAMILIA
           ,STATUS
           ,CONVERT(VARCHAR, ID_DISTRIBUIDOR)+COD_MARCA ID_MARCA
           ,CONVERT(VARCHAR, ID_DISTRIBUIDOR)+COD_GRUPO ID_GRUPO
           ,CONVERT(VARCHAR, ID_DISTRIBUIDOR)+COD_SUBGRUPO ID_SUBGRUPO
           ,CONVERT(VARCHAR, ID_DISTRIBUIDOR)+'-'+COD_FORNECEDOR ID_FORNECEDOR
		   ,GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM PRODUTO_DISTRIBUIDOR B
						WHERE B.AGRUPAMENTO_VARIANTE = ISNULL(AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, ID_DISTRIBUIDOR)+'-'+COD_PROD_DISTR)
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR
						  AND B.COD_PROD_DISTR = A.COD_PROD_DISTR)
;

GO

--IMPORTAR PRODUTO
PRINT 'SALVANDO PRODUTO'
INSERT INTO PRODUTO
	SELECT  (SELECT ID_PRODUTO
					FROM PRODUTO_DISTRIBUIDOR C 
					WHERE C.id_distribuidor = A.ID_DISTRIBUIDOR
					  AND ISNULL(C.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, C.ID_DISTRIBUIDOR)+'-'+C.COD_PROD_DISTR) = ISNULL(A.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, A.ID_DISTRIBUIDOR)+'-'+A.COD_PROD_DISTR)
					  AND C.COD_PROD_DISTR=A.COD_PROD_DISTR)
			ID_PRODUTO
		   ,AGRUPAMENTO_VARIANTE ID_AGRUPAMENTO
           ,DESCR_REDUZIDA_DISTR DESCRICAO
           ,DESCR_COMPLETA_DISTR DESCRICAO_COMPLETA
           ,SKU
           ,DUM14
           ,STATUS
           ,TIPO_PRODUTO
           ,VARIANTE
           ,UNIDADE_VENDA
           ,QUANT_UNID_VENDA
           ,UNIDADE_EMBALAGEM
           ,QUANTIDADE_EMBALAGEM
           ,VOLUMETRIA
           ,DT_INSERT
           ,DT_UPDATE
		   ,GETDATE() DATA_CADASTRO
	FROM #API_PRODUTO_TMP A
	WHERE NOT EXISTS ( SELECT 1 FROM PRODUTO B
						WHERE B.ID_PRODUTO IN (SELECT ID_PRODUTO
												FROM PRODUTO_DISTRIBUIDOR C 
												WHERE C.id_distribuidor = A.ID_DISTRIBUIDOR
												  AND ISNULL(C.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, C.ID_DISTRIBUIDOR)+'-'+C.COD_PROD_DISTR) = ISNULL(A.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, A.ID_DISTRIBUIDOR)+'-'+A.COD_PROD_DISTR)
												  AND C.COD_PROD_DISTR=A.COD_PROD_DISTR) )
;

GO

--ATUALIZAR TABELA DE INTEGRACAO COM DISTRIBUIDOR
PRINT 'ATUALIZADO API_PRODUTO'
UPDATE A
SET
    A.ID_PRODUTO = (SELECT ID_PRODUTO
					FROM PRODUTO_DISTRIBUIDOR C 
					WHERE C.id_distribuidor = B.ID_DISTRIBUIDOR
						AND ISNULL(C.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, C.ID_DISTRIBUIDOR)+'-'+C.COD_PROD_DISTR) = ISNULL(B.AGRUPAMENTO_VARIANTE, CONVERT(VARCHAR, B.ID_DISTRIBUIDOR)+'-'+B.COD_PROD_DISTR)
						AND C.COD_PROD_DISTR=B.COD_PROD_DISTR),
	A.STATUS_APROVADO='A'
FROM
    API_PRODUTO AS A
    INNER JOIN #API_PRODUTO_TMP AS B
        ON A.COD_PROD_DISTR = B.COD_PROD_DISTR
		AND A.ID_DISTRIBUIDOR=B.ID_DISTRIBUIDOR
WHERE (A.ID_PRODUTO IS NULL OR A.ID_PRODUTO='0') 
	  AND A.ID_DISTRIBUIDOR=1
	  ;

GO

--DELETAR TABELA TEMPORAIA
PRINT 'DELETE #API_PRODUTO_TMP'
DROP TABLE #API_PRODUTO_TMP

GO