-- Travar registros 
UPDATE api_produto_estoque SET atualizado='A' WHERE ISNULL(atualizado,'N')='N';

GO

-- Update para atualizar os dados ja existentes
--SELECT A.ID_PRODUTO, A.ID_DISTRIBUIDOR, C.SALDO_ESTOQUE QTD_ESTOQUE, GETDATE() ULTIMA_ATUALIZACAO
UPDATE A
SET A.QTD_ESTOQUE = C.SALDO_ESTOQUE, ULTIMA_ATUALIZACAO = GETDATE()
FROM PRODUTO_ESTOQUE A
INNER JOIN PRODUTO_DISTRIBUIDOR B ON B.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR
				    AND B.ID_PRODUTO=A.ID_PRODUTO
INNER JOIN API_PRODUTO_ESTOQUE C ON  C.ID_DISTRIBUIDOR=B.ID_DISTRIBUIDOR
							     AND C.COD_PROD_DISTR=B.COD_PROD_DISTR
							     AND C.AGRUPAMENTO_VARIANTE=B.AGRUPAMENTO_VARIANTE
WHERE C.ATUALIZADO='A' AND C.SALDO_ESTOQUE<>A.QTD_ESTOQUE
;

GO

-- Insert para atualizar os dados ja existentes
INSERT INTO PRODUTO_ESTOQUE
SELECT B.ID_PRODUTO, A.ID_DISTRIBUIDOR, A.SALDO_ESTOQUE QTD_ESTOQUE, GETDATE() ULTIMA_ATUALIZACAO
FROM API_PRODUTO_ESTOQUE A
INNER JOIN PRODUTO_DISTRIBUIDOR B ON A.ID_DISTRIBUIDOR=B.ID_DISTRIBUIDOR
							     AND A.COD_PROD_DISTR=B.COD_PROD_DISTR
							     AND A.AGRUPAMENTO_VARIANTE=B.AGRUPAMENTO_VARIANTE
WHERE A.ATUALIZADO='A'
  AND NOT EXISTS (SELECT 1
				  FROM PRODUTO_ESTOQUE C
				  WHERE B.ID_DISTRIBUIDOR=C.ID_DISTRIBUIDOR
				    AND B.ID_PRODUTO=C.ID_PRODUTO)
;

GO
