USE [B2BTESTE2]
GO

PRINT 'SALVANDO TABELA_PRECO'
INSERT INTO TABELA_PRECO
	SELECT  ID_DISTRIBUIDOR,
			COD_TABELA ID_TABELA_PRECO,
			DESCRI_TABELA NOME_TABELA_PRECO,
			TABELA_PADRAO,
			STATUS,
			CONVERT(VARCHAR(10), DT_INICIO, 103) DT_INICIO,
			CONVERT(VARCHAR(10), DT_FIM, 103) DT_FIM,
			GETDATE() DT_CADASTRO,
			GETDATE() DT_UPDATE
	FROM API_TABELA_PRECO A
	WHERE NOT EXISTS ( SELECT 1 FROM TABELA_PRECO B
						WHERE B.ID_TABELA_PRECO = A.COD_TABELA
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR )
;


--ATUALIZAR TABELA_PRECO INTEGRADA PELO DISTRIBUIDOR
PRINT 'ATUALIZADO TABELA_PRECO'
UPDATE A
SET 		A.NOME_TABELA_PRECO = B.DESCRI_TABELA,
			A.TABELA_PADRAO = B.TABELA_PADRAO,
			A.STATUS = B.STATUS,
			A.DT_INICIO = CONVERT(VARCHAR(10), B.DT_INICIO, 103),
			A.DT_FIM = CONVERT(VARCHAR(10), B.DT_FIM, 103),
			A.DT_UPDATE = GETDATE()
FROM
    TABELA_PRECO AS A
    INNER JOIN API_TABELA_PRECO AS B
        ON A.ID_TABELA_PRECO = B.COD_TABELA
	   AND A.id_distribuidor = B.ID_DISTRIBUIDOR 
WHERE 1=1
	 ;

GO

--IMPORTAR TABELA_PRECO_PRODUTO CASO NAO TENHA
PRINT 'SALVANDO TABELA_PRECO_PRODUTO'
INSERT INTO TABELA_PRECO_PRODUTO
	SELECT  A.ID_DISTRIBUIDOR,
			A.COD_TABELA ID_TABELA_PRECO,
			C.ID_PRODUTO,
			A.PRECO_TABELA,
			GETDATE() DT_CADASTRO,
			GETDATE() DT_UPDATE
	FROM API_TABELA_PRECO_ITEM A
	INNER JOIN PRODUTO_DISTRIBUIDOR C ON C.AGRUPAMENTO_VARIANTE=A.AGRUPAMENTO_VARIANTE
									  AND C.COD_PROD_DISTR=A.COD_PROD_DISTR
									  AND C.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR
	WHERE NOT EXISTS ( SELECT 1 FROM TABELA_PRECO_PRODUTO B
						WHERE B.ID_TABELA_PRECO = A.COD_TABELA
						  AND B.id_distribuidor = A.ID_DISTRIBUIDOR
						  AND B.ID_PRODUTO = C.ID_PRODUTO )
;
GO

--ATUALIZAR TABELA_PRECO_PRODUTO INTEGRADA PELO DISTRIBUIDOR
PRINT 'ATUALIZADO TABELA_PRECO_PRODUTO'
UPDATE A
SET 		A.PRECO_TABELA = B.PRECO_TABELA,
			A.DT_UPDATE = GETDATE() 
FROM
    TABELA_PRECO_PRODUTO AS A
    INNER JOIN (
					SELECT	A.ID_DISTRIBUIDOR, A.COD_TABELA ID_TABELA_PRECO, C.ID_PRODUTO, A.PRECO_TABELA
					FROM API_TABELA_PRECO_ITEM A
					INNER JOIN PRODUTO_DISTRIBUIDOR C ON C.AGRUPAMENTO_VARIANTE=A.AGRUPAMENTO_VARIANTE
													  AND C.COD_PROD_DISTR=A.COD_PROD_DISTR
													  AND C.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR
					WHERE 1=1) AS B
									ON A.ID_TABELA_PRECO = B.ID_TABELA_PRECO
								   AND A.id_distribuidor = B.ID_DISTRIBUIDOR 
								   AND A.ID_PRODUTO = B.ID_PRODUTO 
WHERE A.PRECO_TABELA <> B.PRECO_TABELA
	 ;

GO