PRINT 'SALVANDO GRUPO'
INSERT INTO GRUPO
SELECT  0 ID_DISTRIBUIDOR,
		( ROW_NUMBER() OVER(ORDER BY gp.descricao desc) ) + (SELECT ISNULL(MAX(E.id_grupo),0) FROM GRUPO E WHERE E.tipo_pai=1 and E.id_distribuidor=0) id_grupo,
		(SELECT MAX(ID_TIPO) FROM TIPO C WHERE C.id_distribuidor=0 and C.PADRAO='S' and C.status='A') tipo_pai,
		UPPER(GP.descricao) descricao,
		'A' STATUS,
		GETDATE() DATA_CADASTRO
FROM PRODUTO_DISTRIBUIDOR A
INNER JOIN GRUPO GP ON GP.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR AND GP.id_grupo=A.ID_GRUPO
INNER JOIN SUBGRUPO SB ON SB.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR AND SB.id_subgrupo=A.id_subgrupo
WHERE NOT EXISTS (  SELECT 1
					FROM GRUPO D
					WHERE D.tipo_pai IN (SELECT MAX(ID_TIPO) FROM TIPO C WHERE C.id_distribuidor=0 and C.PADRAO='S' and C.status='A')
					  AND D.id_distribuidor=0 
					  AND D.status='A'
					  AND UPPER(D.descricao)=UPPER(GP.descricao))
group by GP.descricao
;

PRINT 'SALVANDO SUBGRUPO'
INSERT INTO SUBGRUPO
	SELECT  0 ID_DISTRIBUIDOR,
			( ROW_NUMBER() OVER(ORDER BY SB.descricao desc) ) + + (SELECT ISNULL(MAX(E.id_subgrupo),0) FROM SUBGRUPO E WHERE E.id_distribuidor=0) id_subgrupo,
			UPPER(SB.descricao) descricao,
			'A' STATUS,
			GETDATE() DATA_CADASTRO
	FROM PRODUTO_DISTRIBUIDOR A
	INNER JOIN GRUPO GP ON GP.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR AND GP.id_grupo=A.ID_GRUPO
	INNER JOIN SUBGRUPO SB ON SB.ID_DISTRIBUIDOR=A.ID_DISTRIBUIDOR AND SB.id_subgrupo=A.id_subgrupo
	WHERE NOT EXISTS (  SELECT 1
						FROM SUBGRUPO D
						WHERE D.id_distribuidor=0 
						  AND D.status='A'
						  AND UPPER(D.descricao)=UPPER(SB.descricao))
	group by SB.descricao

;

PRINT 'SALVANDO GRUPO-PRODUTO_DISTRIBUIDOR'
UPDATE PRODUTO_DISTRIBUIDOR SET 
ID_GRUPO_ROOT =
		(SELECT ( SELECT D.id_grupo
					FROM GRUPO D
					WHERE D.tipo_pai IN (SELECT MAX(ID_TIPO) FROM TIPO C WHERE C.id_distribuidor=0 and C.PADRAO='S' and C.status='A')
						AND D.id_distribuidor=0 
						AND D.status='A'
						AND UPPER(D.descricao)=UPPER(GP1.DESCRICAO)
						) ID
		 FROM GRUPO GP1
		 WHERE GP1.ID_DISTRIBUIDOR=PRODUTO_DISTRIBUIDOR.ID_DISTRIBUIDOR
		   AND GP1.id_grupo=PRODUTO_DISTRIBUIDOR.ID_GRUPO) 
WHERE ID_GRUPO_ROOT IS NULL
;

PRINT 'SALVANDO SUBGRUPO-PRODUTO_DISTRIBUIDOR'
UPDATE PRODUTO_DISTRIBUIDOR SET 
ID_SUBGRUPO_ROOT =
		(SELECT ( SELECT D.id_subgrupo
			FROM SUBGRUPO D
			WHERE D.id_distribuidor=0 
				AND D.status='A'
				AND RTRIM(LTRIM(UPPER(D.descricao)))=RTRIM(LTRIM(UPPER(GP1.DESCRICAO)))
				) ID
		 FROM SUBGRUPO GP1
		 WHERE GP1.ID_DISTRIBUIDOR=PRODUTO_DISTRIBUIDOR.ID_DISTRIBUIDOR
		   AND GP1.id_subgrupo=PRODUTO_DISTRIBUIDOR.ID_SUBGRUPO) 
WHERE ID_SUBGRUPO_ROOT IS NULL
;


PRINT 'SALVANDO GRUPO-SUBGRUPO'
INSERT INTO GRUPO_SUBGRUPO
	SELECT  0 ID_DISTRIBUIDOR,
			ID_GRUPO_ROOT id_grupo,
			ID_SUBGRUPO_ROOT id_subgrupo,
			'A' STATUS
	FROM PRODUTO_DISTRIBUIDOR A
	WHERE NOT EXISTS ( SELECT 1 FROM GRUPO_SUBGRUPO GB
						WHERE GB.id_subgrupo = A.ID_SUBGRUPO_ROOT
						  AND GB.id_grupo = A.ID_GRUPO_ROOT
						  AND GB.id_distribuidor = 0 )
	GROUP BY ID_GRUPO_ROOT, ID_SUBGRUPO_ROOT
;

PRINT 'SALVANDO PRODUTO_SUBGRUPO'
INSERT INTO PRODUTO_SUBGRUPO
	SELECT  ID_PRODUTO CODIGO_PRODUTO,
			(SELECT MAX(SKU) FROM PRODUTO B WHERE B.ID_PRODUTO=A.ID_PRODUTO) SKU,
			0 ID_DISTRIBUIDOR,
			ID_SUBGRUPO_ROOT id_subgrupo,
			'A' STATUS
	FROM PRODUTO_DISTRIBUIDOR A
	WHERE NOT EXISTS ( SELECT 1 FROM PRODUTO_SUBGRUPO GB
						WHERE GB.id_subgrupo = A.ID_SUBGRUPO_ROOT
						  AND GB.CODIGO_PRODUTO = A.ID_PRODUTO
						  AND GB.id_distribuidor = 0 )



