openapi: 3.0.0

info:
  title: "API do projeto B2B"
  description: "Documentação da API do projeto B2B 2.0."
  version: 0.2.0

tags:
  - name: "Sessão-out marketplace"
    description: "Encerra a sessão do marketplace"

servers:
  - url: 'https://wsmarketplace-dev.guarany.com.br/api/v1'
    description: Production server

paths:
  
  /marketplace/usuarios/sessoes/finalizacao:
  
    post:
      tags:
        - "Sessão-out marketplace"
      summary: POST - Finalização de sessão.

      description: "
                        * Tabelas Alteradas: SESSAO
                    "

      requestBody:
        description: "Request Body."
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body-request'
            examples:
              Sessão out Comum:  # <--- Nome do Exemplo dado
                summary: Sessão out correto
                value:
                  # vv Payload do exemplo vv
                  token_aparelho: "968c8039-2853-4414-ac12-822a0dfcf66a"
                  navegador: "web-ios-968c8039-2853-4414-ac12-822a0dfcf66a"
 
      responses:
        '200':
          description: "Sucesso na operação"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Resposta_Tudo-ok'

              examples:
                
                Resposta_Tudo-ok:
                  summary: "Resposta: tudo ok"
                  value:
                    # vv Payload do exemplo vv
                    Descricao-detalhada:
                      descricao: "Caso a request ocorra sem nenhum problema."
                    Saida-Real:
                      status: 200
                      resposta: 
                        tipo: 1
                        descricao: "Sessão finalizada."

        '400':
          description: "Erro de sintaxe do usuário"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Resposta_Acao-especifica-negada-erro'
                 
              examples:

                Resposta_Acao-especifica-negada-erro:
                  summary: "Resposta: Ação especifica negada por erro"
                  value:
                    # vv Payload do exemplo vv
                    Descricao-detalhada:
                      descricao: "Caso o token seja enviado na request, ele seja validado, tenha permissão de realizar ação, mas tente fazer algo que não pode acontecer."
                    Saida-Real:
                      status: 400
                      resposta: 
                        tipo: 13
                        descricao: "Ação recusada: Sessão não existente."
                
components:
      
  schemas:

    # Response Body padrão
    Body-request:
      type: object
      properties:
        
        token_aparelho: 
          type: string
          description: "Token intrínseco do aparelho utilizado. (Obrigatorio)"
        
        navegador:
          type: string
          description: "Meio utilizado para acessar o marketplace. (Opcional)"
          default: 'APP'

      required:
        - token_aparelho

      example:

        token_aparelho: "968c8039-2853-4414-ac12-822a0dfcf66a"
        navegador: "web-ios-968c8039-2853-4414-ac12-822a0dfcf66a"
 
    # Resposta para Tudo ok
    Resposta_Tudo-ok:
      type: object
      description: "Caso a request ocorra sem nenhum problema."

      properties:
        
          status:
            type: integer
            description: "Codigo HTTP da resposta enviada"
          
          resposta: 
            type: object
            description: "Utilizado para informar o tipo da resposta e uma descrição da mesma"
            properties:
          
              tipo: 
                type: string
                description: "Tipo da resposta apresentada"
          
              descricao:
                type: string
                description: "Mensagem descrevendo a situação da resposta"
      
      example:

        status: 200
        resposta: 
          tipo: 1
          descricao: "Sessão finalizada."

    # Resposta para ação especifica negada por erro
    Resposta_Acao-especifica-negada-erro:
      type: object
      description: Caso o token seja enviado na request, ele seja validado, tenha permissão de realizar ação, mas tente fazer algo que não pode acontecer.
      properties:
        
        status:
          type: integer
          description: "Codigo HTTP da resposta enviada"
        
        resposta: 
          type: object
          description: "Utilizado para informar o tipo da resposta e uma descrição da mesma"
          properties:
        
            tipo: 
              type: string
              description: "Tipo da resposta apresentada"
        
            descricao:
              type: string
              description: "Mensagem descrevendo a situação da resposta"

      example:

        status: 400
        resposta: 
          tipo: 13
          descricao: "Ação recusada: Mensagem especifica."